import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/Navbar";
import { ConnectionContextProvider } from "@/context/isConnected"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // Add the weights you need
  variable: "--font-poppins", // Optional: for using as a CSS variable
});

export const metadata: Metadata = {
  title: "Lisk Earn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ConnectionContextProvider>
          {children}
          <Toaster />
        </ConnectionContextProvider>
      </body>
    </html>
  );
}